name: Ping Health Check

# This workflow pings the health check endpoint every 4 minutes to keep the service alive
# and verify that it's functioning properly. It includes a retry mechanism to ensure success.
on:
  schedule:
    - cron: '*/4 * * * *' # every 4 minutes
  workflow_dispatch: # Allow manual triggering from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /up with retries
        run: |
          MAX_ATTEMPTS=10
          ATTEMPT=1

          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            echo "Attempt $ATTEMPT of $MAX_ATTEMPTS"
            status=$(curl -o /dev/null -s -w "%{http_code}\n" https://noteflow-api-jefi.onrender.com/up)
            
            if [ "$status" = "200" ]; then
              echo "Health check successful: HTTP 200"
              exit 0
            else
              echo "Health check failed: HTTP $status, retrying in 10 seconds..."
              sleep 10
              ATTEMPT=$((ATTEMPT+1))
            fi
          done

          echo "Health check failed after $MAX_ATTEMPTS attempts"
          exit 1
