name: Ping Health Check

on:
  schedule:
    - cron: '*/12 * * * *' # every 12 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /up
        run: |
          status=$(curl -o /dev/null -s -w "%{http_code}\n" https://noteflow-api-jefi.onrender.com/up)
          if [ "$status" != "200" ]; then
            echo "Health check failed: HTTP $status"
            exit 1
          fi
